name: flutter_speech
description: Flutter plugin to support voice recognition on Android, iOS and Mac OSX
version: 2.0.0
author: jaumard <jimmy.aumard@gmail.com>
homepage: https://github.com/jaumard/flutter_speech_recognition

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      ios:
        pluginClass: FlutterSpeechRecognitionPlugin
      macos:
        pluginClass: FlutterSpeechRecognitionPlugin
      android:
        package: com.flutter.speech_recognition.flutter_speech
        pluginClass: FlutterSpeechRecognitionPlugin
    #macosPrefix: Flutter
    #iosPrefix: Flutter
    #pluginClass: SpeechRecognitionPlugin
